In [26]:
import numpy as np
import time
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm, trange

np.random.seed(20240454)

In [ ]:
#==============1-1==============
def prefixAverages1(X, n):
    A = np.zeros(n)
    for i in range(n):
        sum = 0
        for j in range(i):
            sum += X[j]
        A[i] = sum / (i + 1)
    return A

def prefixAverages2(X, n):
    A = np.zeros(n)
    sum = 0
    for i in range(n):
        sum += X[i]
        A[i] = sum / (i + 1)
    return A

n = 2 ** 6
slow = np.zeros(1000)
optimized = np.zeros(1000)
for i in trange(1000):
    X = np.random.uniform(0, 1, n)
    start = time.perf_counter()
    prefixAverages1(X, n)
    slow[i] = time.perf_counter() - start

    start = time.perf_counter()
    prefixAverages2(X, n)
    optimized[i] = time.perf_counter() - start

plt.hist(slow / optimized, color='red', label='slow / optimized', bins=1000)
plt.legend()
plt.xlabel("Time")
plt.ylabel("Freq")
plt.savefig("./ratio_hist.jpg")

plt.clf()

minTime = list()
maxTime = list()
avgTime = list()
for i in trange(4, 9):
    n = 2 ** i
    slow = np.zeros(1000)
    optimized = np.zeros(1000)
    for j in range(1000):
        X = np.random.uniform(0, 1, n)
        
        start = time.perf_counter()
        prefixAverages1(X, n)
        slow[j] = time.perf_counter() - start
        
        start = time.perf_counter()
        prefixAverages2(X, n)
        optimized[j] = time.perf_counter() - start
    minTime.append((slow / optimized).min())
    maxTime.append((slow / optimized).max())
    avgTime.append((slow / optimized).mean())
    
nSize = [2 ** i for i in range(4, 9)]

plt.plot(nSize, minTime, marker='o', label='Min Time')
plt.plot(nSize, maxTime, marker='s', label='Max Time')
plt.plot(nSize, avgTime, marker='^', label='Average Time')
plt.xlabel("n")
plt.ylabel("time")
plt.xscale("log", base=2)
plt.yscale("log")
plt.legend()
plt.savefig("./ratio plot.jpg")

plt.clf()

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

<Figure size 640x480 with 0 Axes>

In [ ]:
#==============1-2==============
def movingAverages1(X, n, k):
    A = np.zeros(n)
    for i in range(n):
        if i < k - 1:
            A[i] = np.mean(X[:i + 1])
        else:
            A[i] = np.mean(X[i - k + 1:i + 1])
    return A

def movingAverages2(X, n, k):
    A = np.zeros(n)
    move = 0
    for i in range(n):
        move += X[i]
        if k <= i:
            move -= X[i - k]
        A[i] = move / min(i + 1, k)
    return A

n = 2 ** 5
k = 2 ** 4
slow = np.zeros(1000)
optimized = np.zeros(1000)
for i in trange(1000):
    X = np.random.uniform(0, 1, n)
    start = time.perf_counter()
    movingAverages1(X, n, k)
    slow[i] = time.perf_counter() - start

    start = time.perf_counter()
    movingAverages2(X, n, k)
    optimized[i] = time.perf_counter() - start

plt.hist(slow / optimized, color='red', label='slow / optimized', bins = 1000)
plt.legend()
plt.xlabel("Time Ratio")
plt.ylabel("Freq")
plt.savefig("./ratio_hist2.jpg")

plt.clf()

minTime = list()
maxTime = list()
avgTime = list()
k = 2 ** 3
for i in trange(4, 9):
    n = 2 ** i
    slow = np.zeros(1000)
    optimized = np.zeros(1000)
    for j in range(1000):
        X = np.random.uniform(0, 1, n)
        start = time.perf_counter()
        movingAverages1(X, n, k)
        slow[j] = time.perf_counter() - start
        
        start = time.perf_counter()
        movingAverages2(X, n, k)
        optimized[j] = time.perf_counter() - start
    minTime.append((slow / optimized).min())
    maxTime.append((slow / optimized).max())
    avgTime.append((slow / optimized).mean())
    
nSize = [2 ** i for i in range(4, 9)]

plt.plot(nSize, minTime, marker='o', label='Min Time')
plt.plot(nSize, maxTime, marker='s', label='Max Time')
plt.plot(nSize, avgTime, marker='^', label='Average Time')
plt.xlabel("n")
plt.ylabel("time")
plt.xscale("log", base=2)
plt.yscale("log")
plt.legend()
plt.savefig("./ratio plot2.jpg")

plt.clf()

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

<Figure size 640x480 with 0 Axes>

In [ ]:
#==============1-3==============
def findMissing(A, n):
    return (n * (n - 1) // 2) - sum(A)

six = np.zeros(1000)
n = 2 ** 6
for i in trange(1000):
    A = list(range(n))
    np.random.shuffle(A)
    A.pop()
    start = time.perf_counter()
    findMissing(A, n)
    six[i] = time.perf_counter() - start

seven = np.zeros(1000)
n = 2 ** 7
for i in trange(1000):
    A = list(range(n))
    np.random.shuffle(A)
    A.pop()
    start = time.perf_counter()
    findMissing(A, n)
    seven[i] = time.perf_counter() - start

plt.hist(seven / six, color='red', label='2^7/2^6')
plt.legend()
plt.xlabel("Time Ratio")
plt.ylabel("Freq")

plt.savefig("./ratio_hist3.jpg")
plt.clf()

three = np.zeros(1000)
n = 2 ** 3
for i in trange(1000):
    A = list(range(n))
    np.random.shuffle(A)
    A.pop()
    start = time.perf_counter()
    findMissing(A, n)
    three[i] = time.perf_counter() - start

minTime = list()
maxTime = list()
avgTime = list()
for i in trange(4, 9):
    n = 2 ** i
    find = np.zeros(1000)
    for j in range(1000):
        X = np.random.uniform(0, 1, n)
        start = time.perf_counter()
        findMissing(X, n)
        find[j] = time.perf_counter() - start
    minTime.append((find / three).min())
    maxTime.append((find / three).max())
    avgTime.append((find / three).mean())
    
nSize = [2 ** i / 2 ** 3 for i in range(4, 9)]

plt.plot(nSize, minTime, marker='o', label='Min Time')
plt.plot(nSize, maxTime, marker='s', label='Max Time')
plt.plot(nSize, avgTime, marker='^', label='Average Time')
plt.xlabel("2^n/2^3")
plt.ylabel("ratio")
plt.xscale("log", base=2)
plt.yscale("log")
plt.legend()
plt.savefig("./ratio plot3.jpg")

plt.clf()

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

<Figure size 640x480 with 0 Axes>

In [ ]:
#==============1-4==============
def countOnes(A, n):
    loc = n - 1
    cnt = 0
    for i in range(n):
        while A[i][loc] == 0:
            if loc == 0:
                return cnt
            loc -= 1
        cnt += loc + 1
    return cnt

def countOnesButSlow(A, n):
    c = 0
    for i in range(n):
        j = 0
        while j < n and A[i][j] == 1:
            c += 1
            j += 1
    return c

n = 2 ** 6
slow = np.zeros(1000)
optimized = np.zeros(1000)
for i in trange(1000):
    A = np.zeros((n, n))
    numOfOne = sorted(np.random.randint(0, n + 1, size=n), reverse=True)
    for j in range(0, n):
        A[j, :numOfOne[j]] = 1
    
    start = time.perf_counter()
    countOnesButSlow(A, n)
    slow[i] = time.perf_counter() - start

    start = time.perf_counter()
    countOnes(A, n)
    optimized[i] = time.perf_counter() - start
    
plt.hist(slow / optimized, color='red', label='countOnesButSlow / countOnes')
plt.legend()
plt.xlabel("Time Ratio")
plt.ylabel("Freq")
plt.savefig("./ratio_hist4.jpg")

plt.clf()

minTime = list()
maxTime = list()
avgTime = list()
for i in trange(4, 9):
    n = 2 ** i
    slow = np.zeros(1000)
    optimized = np.zeros(1000)
    for j in range(1000):
        A = np.zeros((n, n))
        numOfOne = sorted(np.random.randint(0, n + 1, size=n), reverse=True)
        for k in range(0, n):
            A[k, :numOfOne[k]] = 1
        
        start = time.perf_counter()
        countOnesButSlow(A, n)
        slow[j] = time.perf_counter() - start

        start = time.perf_counter()
        countOnes(A, n)
        optimized[j] = time.perf_counter() - start
    minTime.append((slow / optimized).min())
    maxTime.append((slow / optimized).max())
    avgTime.append((slow / optimized).mean())
    
nSize = [2 ** i for i in range(4, 9)]

plt.plot(nSize, minTime, marker='o', label='Min Time')
plt.plot(nSize, maxTime, marker='s', label='Max Time')
plt.plot(nSize, avgTime, marker='^', label='Average Time')
plt.xlabel("n")
plt.ylabel("ratio")
plt.xscale("log", base=2)
plt.yscale("log")
plt.legend()
plt.savefig("./ratio plot4.jpg")

plt.clf()

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

<Figure size 640x480 with 0 Axes>

In [22]:
#==============2-1===============
def gcd1(a, b):
    if b == 0:
        return a
    
    print(f"computing gcd1({a}, {b}), ", end='')
    
    return gcd1(b, a % b)

def gcd2(a, b):
    if a == b:
        return a
    
    print(f"computing gcd2({a}, {b}), ", end='')
    
    if a > b:
        return gcd2(a - b, b)
    else:
        return gcd2(a, b - a)

print(f"and gcd1(493, 33) is {gcd1(493, 33)}")
print()
print(f"and gcd2(493, 33) is {gcd2(493, 33)}")
print()
print(f"and gcd1(225, 13) is {gcd1(225, 13)}")
print()
print(f"and gcd2(225, 13) is {gcd2(225, 13)}")
print()

computing gcd1(493, 33), computing gcd1(33, 31), computing gcd1(31, 2), computing gcd1(2, 1), and gcd1(493, 33) is 1

computing gcd2(493, 33), computing gcd2(460, 33), computing gcd2(427, 33), computing gcd2(394, 33), computing gcd2(361, 33), computing gcd2(328, 33), computing gcd2(295, 33), computing gcd2(262, 33), computing gcd2(229, 33), computing gcd2(196, 33), computing gcd2(163, 33), computing gcd2(130, 33), computing gcd2(97, 33), computing gcd2(64, 33), computing gcd2(31, 33), computing gcd2(31, 2), computing gcd2(29, 2), computing gcd2(27, 2), computing gcd2(25, 2), computing gcd2(23, 2), computing gcd2(21, 2), computing gcd2(19, 2), computing gcd2(17, 2), computing gcd2(15, 2), computing gcd2(13, 2), computing gcd2(11, 2), computing gcd2(9, 2), computing gcd2(7, 2), computing gcd2(5, 2), computing gcd2(3, 2), computing gcd2(1, 2), and gcd2(493, 33) is 1

computing gcd1(225, 13), computing gcd1(13, 4), computing gcd1(4, 1), and gcd1(225, 13) is 1

computing gcd2(225, 13), comp

In [23]:
#==============2-2===============
def divide(a, b):
    if a < b:
        return (0, a)
    
    print(f"computing divide({a}, {b}), ", end='')
    
    q, r = divide(a - b, b)
    return (q + 1, r)

q, r = divide(413, 31)
print(f"and divide(413, 31) is quotient: {q}, remainder: {r}")
print()
q, r = divide(1325, 113)
print(f"and divide(1325, 113) is quotient: {q}, remainder: {r}")
print()

computing divide(413, 31), computing divide(382, 31), computing divide(351, 31), computing divide(320, 31), computing divide(289, 31), computing divide(258, 31), computing divide(227, 31), computing divide(196, 31), computing divide(165, 31), computing divide(134, 31), computing divide(103, 31), computing divide(72, 31), computing divide(41, 31), and divide(413, 31) is quotient: 13, remainder: 10

computing divide(1325, 113), computing divide(1212, 113), computing divide(1099, 113), computing divide(986, 113), computing divide(873, 113), computing divide(760, 113), computing divide(647, 113), computing divide(534, 113), computing divide(421, 113), computing divide(308, 113), computing divide(195, 113), and divide(1325, 113) is quotient: 11, remainder: 82



In [24]:
#==============3-1===============
def spiral(n, m):
    A = np.zeros((n, m), dtype=int)
    x, y = 0, 0
    togo = ((1, 0), (0, 1), (-1, 0), (0, -1))
    now = 0
    for i in range(1, n * m + 1):
        A[y][x] = i
        nx, ny = x + togo[now][0], y + togo[now][1]
        if m <= nx or n <= ny or A[ny][nx] != 0:
            now = (now + 1) % 4
        x += togo[now][0]
        y += togo[now][1]
    return A

print(spiral(10, 4))

[[ 1  2  3  4]
 [24 25 26  5]
 [23 40 27  6]
 [22 39 28  7]
 [21 38 29  8]
 [20 37 30  9]
 [19 36 31 10]
 [18 35 32 11]
 [17 34 33 12]
 [16 15 14 13]]


In [27]:
#==============3-2===============
n = 10 ** 6
toHist = np.zeros(n)
for i in trange(n):
    # A = np.zeros((100, 100))
    howMuch = np.random.randint(5, 11)
    loc = np.random.choice(range(10000), howMuch, replace=False)
    # A.flat[loc] = 1
    nonzeroOffset = np.sum(loc)
    locOffset = ((howMuch * 2) * (howMuch * 2 - 1)) // 2
    toHist[i] = nonzeroOffset / locOffset

plt.hist(toHist, color='red', label='offset ratio')
plt.legend()
plt.xlabel("Time Ratio")
plt.ylabel("Freq")

plt.savefig("./sparse hist1.jpg")
plt.clf()

n = 10 ** 6
toHist = np.zeros(n)
for i in trange(n):
    # A = np.zeros((100, 100))
    howMuch = np.random.randint(10, 21)
    loc = np.random.choice(range(10000), howMuch, replace=False)
    # A.flat[loc] = 1
    nonzeroOffset = np.sum(loc)
    locOffset = ((howMuch * 2) * (howMuch * 2 - 1)) // 2
    toHist[i] = nonzeroOffset / locOffset

plt.hist(toHist, color='red', label='offset ratio')
plt.legend()
plt.xlabel("Offset Ratio")
plt.ylabel("Freq")

plt.savefig("./sparse hist2.jpg")
plt.clf()

  0%|          | 0/1000000 [00:00<?, ?it/s]

  0%|          | 0/1000000 [00:00<?, ?it/s]

<Figure size 640x480 with 0 Axes>